 
###
### ADMIN movie
###



### GET all movie
GET http://localhost:5000/api/movies/
###


#Create new movie
POST http://localhost:5000/api/admin/movies/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliMjc3NmYzMGVmMWIxYTk2OGUzZDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNjY0MjV9.jaexCa2U-YXDsfRq2koWw8ykajb4zu9G0C0mh7etzG4

{
    "name" : "Ấu Trùng Lava: Mặt Dây Chuyền 4",
    "other_name" : "Larva Pendant",
    "likes" : 0,
    "views" : 1,
    "type" : "Phim lẻ",
    "year" : "2022",
    "duration" : 33,
    "description" : "Phần phim ngắn ngớ ngẩn tiếp theo của “Đảo ấu trùng” và “Bộ phim Đảo ấu trùng” xoay quanh những sự cố vụng về của đôi bạn hay xì hơi Đỏ và Vàng trong thành phố.",
    "cast" :  [{"name": "Đang cập nhật"}],    
    "genres" : [
        ],
    "comments": []
    ,
    "language" : "Tiếng Việt",
    "episode" : [
        {
            "name": "Full",
            "URL_episode": "youtube.com/embed/4hhOZ1QWU4g"
        }
    ], 
    "URL_image": "https://static.247phim.com/165095/conversions/62948cc830b42_lava2022-435_627.jpg"
}
###


### Delete movie
DELETE http://localhost:5000/api/admin/movies/629be27a2f6f023db693b9a9/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliMjc3NmYzMGVmMWIxYTk2OGUzZDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNjg4MjR9.TXy1JdtBPx8zm0-ZDJI_z2KpRQfPe9ld2VwGXIM_aZA
###

### Update movie - add mew comment
PATCH http://localhost:5000/api/admin/movies/629bc9049dc870b49e3330ba/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliYjBhMmZlZTM0OTkzYmExZWNhYmIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNzQyOTN9.vzb8w1c3f8I0CJUdpSc0RmQDL9jWiJuC8mk8wkCSRAA

{
    "likes" : 1
}
###





###
### ADMIN user
###

### GET all user
GET http://localhost:5000/api/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliYjBhMmZlZTM0OTkzYmExZWNhYmIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzODMxOTN9.A213gn4zSEr35Bi-GkyryE6AbKMaEPKW0wMeTPdL1eg
###

### Locked a user 
PATCH  http://localhost:5000/api/admin/users/locked/629bb098fee34993ba1ecab7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliYjBhMmZlZTM0OTkzYmExZWNhYmIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNzA2NDJ9.EQkD2JBzXXXcNX49NapERrdgnrFeBEHg0nTNv3tV7Cs
###


### Removed a user
PATCH  http://localhost:5000/api/admin/users/removed/629bb098fee34993ba1ecab7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliYjBhMmZlZTM0OTkzYmExZWNhYmIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNzQyOTN9.vzb8w1c3f8I0CJUdpSc0RmQDL9jWiJuC8mk8wkCSRAA
###




###
### ADMIN SLIDE
###

### Add new slide
POST http://localhost:5000/api/admin/slides/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliMjc3NmYzMGVmMWIxYTk2OGUzZDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNjY0MjV9.jaexCa2U-YXDsfRq2koWw8ykajb4zu9G0C0mh7etzG4

{
"URL_image":"https://static.247phim.com/165032/conversions/628b3db7353ce_mami1-1920_660.jpg",
"URL_movie":"https://247phim.com/xemphim/ve-dep-ma-mi-24144",
"name":"Vẻ Đẹp Ma Mị",
"other_name":"Chom Chod"

}
###






### GET all slides
GET http://localhost:5000/api/admin/slides
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliMjc3NmYzMGVmMWIxYTk2OGUzZDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNjY0MjV9.jaexCa2U-YXDsfRq2koWw8ykajb4zu9G0C0mh7etzG4


###
### ADMIN GENRE
###

### Add new genre
POST http://localhost:5000/api/admin/genres/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliMjc3NmYzMGVmMWIxYTk2OGUzZDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNjY0MjV9.jaexCa2U-YXDsfRq2koWw8ykajb4zu9G0C0mh7etzG4

{

"name":"Cổ trang","name_URL":"co-trang"

}
###






### GET all genres
GET http://localhost:5000/api/admin/genres
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliMjc3NmYzMGVmMWIxYTk2OGUzZDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNjY0MjV9.jaexCa2U-YXDsfRq2koWw8ykajb4zu9G0C0mh7etzG4


###
### ADMIN Country
###

### Add new country
POST http://localhost:5000/api/admin/countries/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjljNmRhYzE3OWE4OWFjNjQ1NzhhMjMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQ0MjAwMDJ9.z6ajvWCZKLjuGuwJewIpQwHzNler5hQ8C8FJhtfgzxU

{
    "name":"Việt Nam","name_URL":"viet-nam"
}
###



### GET all countries
GET http://localhost:5000/api/admin/countries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliMjc3NmYzMGVmMWIxYTk2OGUzZDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNjY0MjV9.jaexCa2U-YXDsfRq2koWw8ykajb4zu9G0C0mh7etzG4




###############################################################################################################################################################################################################
### Auth


### Register new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "bachga1",
    "password": "bachga1",
    "email": "bachga1"
}
###


### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "bachga",
    "password": "bachga"
}
###



#####################################################################################################################################################################################################################################################################
### Public


### GET all movie
GET http://localhost:5000/api/movies
###

### GET all slides
GET http://localhost:5000/api/slides
###


### GET all country
GET http://localhost:5000/api/countries
###

### GET all genres
GET http://localhost:5000/api/genres
###


###
GET http://localhost:5000/api/movies?page=2&limit=2
###

###########################################################################################################################################################################################################################################################################################################################################################################
### USER API

### Get Pofile user
GET http://localhost:5000/api/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliYjBhMmZlZTM0OTkzYmExZWNhYmIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzODMxOTN9.A213gn4zSEr35Bi-GkyryE6AbKMaEPKW0wMeTPdL1eg
###

### update user's profile 
POST http://localhost:5000/api/user/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliYjBhMmZlZTM0OTkzYmExZWNhYmIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzODMxOTN9.A213gn4zSEr35Bi-GkyryE6AbKMaEPKW0wMeTPdL1eg

{
    "name" : "Nguyen Thanh Long"
}
###

###Get list movies user liked
GET http://localhost:5000/api/user/like-movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliMjc3NmYzMGVmMWIxYTk2OGUzZDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzMzY1MTN9.E78petYGxllC968hfpgYSY-ga1UWD_n1izeOawUI5Lw
###

###Update list movies user liked
POST http://localhost:5000/api/user/like-movies/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjViMGE5YzA3OThlZWQ5OTcyNTA5NzQiLCJpYXQiOjE2NTI1NjQyNTh9.soBDzoBKhHnPL-BDzHnrusQDm0EQ3Bv2fERnuNQ57vc

{
    "movie_ID" : "625b2a6971a870a1bacc3791"
}
###

### Get list movies user followed
GET http://localhost:5000/api/user/follow-movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjViMGE5YzA3OThlZWQ5OTcyNTA5NzQiLCJpYXQiOjE2NTI1NjQyNTh9.soBDzoBKhHnPL-BDzHnrusQDm0EQ3Bv2fERnuNQ57vc
###

### Update list movies user followed
POST http://localhost:5000/api/user/follow-movies/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjViMGE5YzA3OThlZWQ5OTcyNTA5NzQiLCJpYXQiOjE2NTI1NjQyNTh9.soBDzoBKhHnPL-BDzHnrusQDm0EQ3Bv2fERnuNQ57vc

{
    "movie_ID" : "625b2a6971a870a1bacc3791"
}
###

### Get list movies user viewed
GET http://localhost:5000/api/user/viewed-movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliYjBhMmZlZTM0OTkzYmExZWNhYmIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNzc4MjZ9.xbqmwBa3365yOgBkrliEE7pxui_afnkWjoneIPvGojk
###

### Update list movies user viewed
POST http://localhost:5000/api/user/viewed-movies/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliYjBhMmZlZTM0OTkzYmExZWNhYmIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNzc4MjZ9.xbqmwBa3365yOgBkrliEE7pxui_afnkWjoneIPvGojk

{
    "movie_ID" : "6280bb5e652356b6d58b91f5"
}
###

### Update movie - add new comment
PATCH http://localhost:5000/api/user/movies/629bc9049dc870b49e3330ba/comment/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliYjBhMmZlZTM0OTkzYmExZWNhYmIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTQzNzgxODJ9.phQLFPS3JFb2cuAFGBlyKktAYq4qXe4j8V51aL-3IeE

{
    "body" : "comment 3"
}
###


###
################################################################################################################################################################################################################################################

###
POST http://localhost:5000/api/admin/category/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjg4YTQ2YTZkMzYxZGIyNzQxZjhkMTQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NTMxMjkzNjJ9.HlJmHFQEEFDUL4S9v-vemLRD1TKYGiylF_r32O8d_qE

{
    "name": "Clip ngắn",
    "url": "clip-ngan",
    "group": "TheLoai"
}
###

###
GET http://localhost:5000/api/admin/categories/PhimLe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjg4YTQ2YTZkMzYxZGIyNzQxZjhkMTQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NTMxMjkzNjJ9.HlJmHFQEEFDUL4S9v-vemLRD1TKYGiylF_r32O8d_qE

###
//Categories 
GET http://localhost:5000/api/categories